name: Cloud Hypervisor Cross Build
on: [pull_request, create]

jobs:
  build:
    if: github.event_name == 'pull_request'
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust }}
            target: ${{ matrix.target }}
            override: true
      - name: test
        run: wget http://ftp.us.debian.org/debian/pool/main/d/device-tree-compiler/libfdt1_1.6.0-1_arm64.deb && dpkg-deb -xv libfdt1_1.6.0-1_arm64.deb ./tlibfdt1
      - name: Disable "with-serde" in kvm-bindings
        run: sed -i 's/"with-serde",\ //g' vmm/Cargo.toml
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target=${{ matrix.target }} --no-default-features --features "mmio"
